### ISSUE TITLE
While Typing Cursor Position Returns to Start of Scratchpad

### ISSUE THREAD

**Issue by vostok4** [davidxw/vsscratchpad#2]
VS Community 15.8.3

When I focus the Scratch Pad (I have it docked) and I start typing something, after 1-2 seconds the cursor position automatically returns to the root position.

**Comment by davidxw** [comment]
I have updated Scratchpad (v1.4) with code to better handle cursor positioning - this issue looks to have been occuring when multiple instances of VS were updating the scratchpad file.
